# =========================
# gNB values file for UHD setup with USRP N300 -- n78 band
# =========================
# recommended RF gain values for N300 on FR1
# Avoid setting TX gain above ~30 dB on N3xx at FR1 frequencies to prevent excessive distortion.
# tx_gain: 20–30
# rx_gain: 25–40
# other possible ARFCN: 627000 (3400 MHz), 636666 (3500 MHz), 648000 (3700 MHz)
#

image:
  repository: ghcr.io/ziyad-mabrouk/srsran-gnb-uhd
  tag: v1.0
  #repository: docker.io/r2labuser/srsran-gnb
  #tag: uhd4.8

resources:
  define: false      # If false, no resources section is added
  requests:
    cpu: "50m"
    memory: "3000Mi"
  limits:
    cpu: "5000m"
    memory: "3000Mi"

start:
  gnb: true          # If false, the gNB container will just sleep and not start srsRAN gNB
  logs: true         # If false, the gnb-log container will not be deployed

gnbIp: 10.10.3.231

gnbConfig:
  cu_cp:
    inactivity_timer: 7200
    request_pdu_session_timeout: 30
    amf:
      sctp_rto_initial: 200
      sctp_rto_min: 200
      sctp_rto_max: 2000
      sctp_init_max_attempts: 5
      sctp_hb_interval: 1000
      sctp_assoc_max_retx: 5
      sctp_nodelay: true
      addr: 10.10.3.200
      port: 38412
      bind_addr: 10.10.3.231
      supported_tracking_areas:
        - tac: 1
          plmn_list:
            - plmn: "00101"
              tai_slice_support_list:
                - sst: 1
                - sst: 1
                  sd: "000002"

  ru_sdr:
    device_driver: uhd                # The RF driver name.
    device_args: mgmt_addr=192.168.235.103,addr=192.168.235.103,name=ni-n3xx-31D98C7,product=n300,num_recv_frames=32,num_send_frames=32,recv_frame_size=8000,send_frame_size=8000
    srate: 61.44                      # RF sample rate might need to be adjusted according to selected bandwidth.
    clock: internal
    sync: internal                        
    tx_gain: 35                       # Transmit gain of the RF might need to adjusted to the given situation.
    rx_gain: 60                       # Receive gain of the RF might need to adjusted to the given situation.

  cell_cfg:
    dl_arfcn: 640000                  # ARFCN of the downlink carrier (center frequency).
    band: 78                          # The NR band.
    channel_bandwidth_MHz: 20         # Bandwith in MHz. Number of PRBs will be automatically derived.
    common_scs: 30                    # Subcarrier spacing in kHz used for data.
    plmn: "00101"                     # PLMN broadcasted by the gNB.
    tac: 1                            # Tracking area code (needs to match the core configuration).
    pci: 0                            # added: Physical cell ID.
    pdcch:
      common:
        ss0_index: 0                  # Set search space zero index to match srsUE capabilities
        coreset0_index: 12            # Set search CORESET Zero index to match srsUE capabilities
      dedicated:
        ss2_type: common              # Search Space type, has to be set to common
        dci_format_0_1_and_1_1: false # Set correct DCI format (fallback)
    prach:
      prach_config_index: 1           # Sets PRACH config to match what is expected by srsUE
    pdsch:
      mcs_table: qam64                # Sets PDSCH MCS to 64 QAM
    pusch:
      mcs_table: qam64                # Sets PUSCH MCS to 64 QAM
    slicing:
      - sst: 1
      - sst: 1
        sd: "000002"

  log:
    filename: /tmp/gnb.log
    all_level: warning
    config_level: debug

  metrics:
    enable_log: false
    autostart_stdout_metrics: true
    enable_json: true
    layers:
      enable_app_usage: true
      enable_e1ap: true
      enable_pdcp: true
      enable_sched: true
      enable_rlc: true            
      enable_mac: true            
      enable_executor: true
      enable_du_low: true
      enable_ru: true

  pcap:
    mac_enable: false
    mac_filename: /tmp/gnb_mac.pcap
    ngap_enable: false
    ngap_filename: /tmp/gnb_ngap.pcap

  remote_control:
    bind_addr: 0.0.0.0
    enabled: true

    port: 8001



